name: DailyQuests
main: org.bestservers.DailyQuestsPlugin
version: 1.0.0
api-version: 1.18
depend: [Vault]
softdepend: [Essentials, EssentialsX, Economy, PlaceholderAPI]
commands:
  zadania:
    description: Zarządzanie questami dziennymi
    usage: /zadania [reload|info <id>]
    permission: dailyquests.user
  oddaj:
    description: Rozlicz aktywne questy
    usage: /oddaj
    permission: dailyquests.user
permissions:
  dailyquests.user:
    description: Dostęp do questów i rozliczania
    default: true
  dailyquests.admin:
    description: Zarządzanie pluginem
    default: op
